name: github pages

on:
  push:
    branches:
    - master
    paths:
    - 'docs/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.58.3'

    - name: Prepare Themes
      run: |
        git submodule sync && git submodule update --init

    - name: Disable Jekyll
      run: touch ./docs/public/.nojekyll

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir -s blog -d public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      with:
        emptyCommits: false
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
